databases:
  - name: taskbuddy-db
    databaseName: taskbuddy
    user: taskbuddy_user
    plan: free

services:
  - type: web
    name: taskbuddy-backend
    runtime: python
    region: oregon
    plan: free
    rootDir: taskbuddy
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn taskbuddy.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: taskbuddy-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CLIENT_ORIGIN
        value: "https://task-buddy-lac.vercel.app"

  - type: web
    name: taskbuddy-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: taskbuddy-backend
          property: host
